Remove broken links
zudochkin/awesome-newsletters pull request #151
Opened 2020-12-18 17:12 UTC by pedabraham

In this pull request I deleted 14 links, which were unaccessible or reported some kind of error, like 404.

Resolves #149

2021-01-27 18:49 UTC, ferhatelmas commented on README.md
> -- [Kotlin Weekly](http://www.kotlinweekly.net/). The weekly newsletter for Kotlin developers, with articles, libraries, videos and podcasts from the Kotlin environment.
seems this is good

2021-01-27 18:49 UTC, ferhatelmas commented on README.md
> -- [Insnippets](https://insnippets.com). A daily newsletter with TL;DR information about interesting topics around web development, Devops and distributed systems.
seems only certificate expired

2021-01-27 18:50 UTC, ferhatelmas commented on README.md
> -- [NoSQL Weekly](https://www.nosqlweekly.com/). A free weekly newsletter featuring curated news, articles, new releases, jobs etc related to NoSQL.
certificate issue, this is good

2021-01-27 18:50 UTC, ferhatelmas commented on README.md
> -- [Machine Learnings](http://subscribe.machinelearnings.co/). A weekly roundup of ML & AI news.
good too

2021-01-27 18:51 UTC, ferhatelmas requested changes
thanks, commented for some since they are alive but have issues with certificate, let's keep them for now.

2021-01-28 17:56 UTC, pedabraham commented
hello @ferhatelmas! I restored the links that were incorrectly removed. And I also resolved the merge conflicts.

2021-02-04 14:35 UTC, ferhatelmas approved these changes
LGTM

Thanks for the update.

2021-02-04 14:35 UTC, merged